### PR TITLE
Add middleware to set buffer size to avoid overly many too-small read…

### PR DESCRIPTION
**Pull request by rstclair**
…s of very large uploaded files. LIBTD-1109

### CODE REVIEW

**Comment by pmather** [comment]
It may be worthwhile pinning to this version of Rack (https://github.com/rack/rack/pull/1192), which, as well as incorporating the fix for the original problem, also tunes the buffer size somewhat based upon having tested various values.

**Comment by rstclair** [comment]
If I understand what you're suggesting, I'd be worried about new problems
caused by changing the version of the Rack gem we're using.

**Comment by pmather** [comment]
The version of Rack you are using currently is 2.0.3, released 15 May 2017.  The fix I mention above was merged on 19 July 2017.  On 1 Feb 2018, version 2.0.4 of Rack was released.  Presumably, this contains the fix I alluded to above, so it probably isn't even necessary to pin to a specific commit of Rack, just to "bundle update rack" to get a fixed version.  (In fact, version 2.0.4 of Rack is what I got when installing the Hyrax Gem recently for the vanilla Hyrax 2 application.)

I agree that updating a Gem always brings potential risks but updating is a necessary evil: for fixing security vulnerabilities; improving performance; or just keeping up with the relentless march of semantic versioning when installing new Gems.  (Incidentally, Gem updates are another good reason for adding tests to our code, particularly regression tests.)  According to IAWA's Gemfile and Gemfile.lock, I see no reason it would reject version 2.0.4 of Rack.

Using a version of Rack with the fix for this problem is easy to test and, IMHO, well worth trying before falling back on a workaround (especially when said workaround involves grabbing an arbitrary 100 MiB-sized buffer).

**Comment by rstclair** [comment]
Changes made. No problems found with Rack gem version 2.0.4.

**Pull request merged**
