### PR TITLE
LIBTD-1073: Restore guest column in users table due to Hyrax code dep…

### PR DESCRIPTION
**Pull request by tingtingjh**
…endency

Add updated schema

### CODE REVIEW

**Comment by tingtingjh** [comment]
@pmather I have two concerns need your advice: 
1. I changed db migration directly instead of adding a new migration. My thinking is that at the first place, we should not remove the existing "guest" column and in the production anyway we will rebuild the application from scratch for testing purpose.
2. For displayed User Id column, I purposely hid the user pids, and displayed their emails instead.

Please let me know your thoughts on these.

**Comment by tingtingjh** [comment]
@pmather I have created a new migration instead. Could you take a second look at this PR?

**Comment by pmather** [comment]
@tingtingjh It looks like your recent update has lost the code to hide user PIDs and display e-mails instead. You should reinstate that.

**Comment by tingtingjh** [comment]
@pmather In my previous commit, I semi-hid the PIDs so I changed some of Collin's code. Now I reverted back to the original code so that only emails are displayed. I will add some snapshots soon.

**Comment by tingtingjh** [comment]
view_users

individual_user

**Pull request merged**
