### PR TITLE
Create nested collections when batch importing items

### PR DESCRIPTION
**Pull request by tingtingjh**
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-1545) (:star:)

* Batch import (https://webapps.es.vt.edu/jira/browse/LIBTD-1486) depends on this ticket to its completion.

# What does this Pull Request do? (:star:)
This PR creates intermediate nested collections as well as their parent-child relationships along the path to the file directory holding the item's files when performing batch imports. For example, if the path is "tmp/imports/Ms1990_025_Rudoff/Ms1990_025_Box1/Ms1990_025_Folder2/Ms1990_025_Per_Scrap_B001_F002_001/Access/Ms1990_025_Per_Scrap_B001_F002_001_007.tif", nested collections and their parent-child relationships (Ms1990_025_Rudoff --> Ms1990_025_Box1 --> Ms1990_025_Folder2) will be generated.

# What's the changes? (:star:)

* Change the Collection model to auto-fill several fields upon creation;
* When importing, create nested collections (if not exist yet) as well as the items;
* The nested collections currently have the default type gid, which can be modified later based on the stakeholder's feedback.

# How should this be tested?

* Place the metadata CSV file under appropriate file path;
* Place several folders of item files under appropriate file path;
* Create ultimate parent collection;
* Go to dashboard --> works --> Batch import items and enter the paths,
* Clear out any errors prompted when clicking on "Import" button

# Additional Notes:

* Branch LIBTD-1545.

# Interested parties
Tag (@shabububu ) interested parties

(:star:) Required fields

### CODE REVIEW

**Comment by shabububu** [comment]
I did some initial testing on my local production environment. It worked in the first case, but not in the second. There may be an issue when different subfolders share the same label/name.

I am testing on the Rudoff data. I used two csv manifests, where each manifest had an associated tif file.

Test 1: The manifest I uploaded produced expected results. The manifest directory folder was set to `Ms1990_025_Rudoff/Ms1990_025_Box1`. The associated file was located at `tmp/imports/Ms1990_025_Rudoff/Ms1990_025_Box1/Ms1990_025_Folder1/Ms1990_025_Per_Eph_B001_F001_001/Access/Ms1990_025_Per_Eph_B001_F001_001_002.tif`. The resulting batch import produced a Collection structure: Base Collection --> Ms1990_025_Box1 --> Ms1990_025_Folder1

Test 2: The manifest I uploaded produced unexpected results. The manifest directory folder was set to `Ms1990_025_Rudoff/Ms1990_025_Folder1`. The associated file was located at
`tmp/imports/Ms1990_025_Rudoff/Ms1990_025_Folder1/Ms1990_025_Vons_Dr_F001_001/Access/Ms1990_025_Vons_Dr_F001_001_001.tif`. The new work was added to the existing Collection structure, created from Test 1: Base Collection --> Ms1990_025_Box1 --> Ms1990_025_Folder1

**Comment by tingtingjh** [comment]
@shabububu Have modified PR to resolve the name conflicts issue. Please check again.

**Comment by tingtingjh** [comment]
@shabububu Adopt option #2 from per your suggestion.

**Comment by tingtingjh** [comment]
@shabububu Now It is using the parent collection title instead of the identifier. Please check again.

**Comment by shabububu** [comment]
I retested, and I approve.

**Pull request merged**
