### PR TITLE
Finish adding the 'sort by Title and Data Created' options to the bro…

### PR DESCRIPTION
**Pull request by tingtingjh**
…wsing pages for collections and items

### CODE REVIEW

**Comment by tingtingjh** [comment]
Updated pull request as discussed in the meeting.

**Comment by tingtingjh** [comment]
According to https://wiki.apache.org/solr/CommonQueryParameters#sort, I have to change the "Title" and "Date Created" fields to single-valued fields.

**Comment by whunter** [comment]
Sort by date works perfectly. I'm not seeing a dropdown to sort by Title. I could be doing something incorrectly though. This is what I'm seeing:

screen shot 2017-01-19 at 1 10 32 pm

**Comment by tingtingjh** [comment]
As I mentioned before, as Curation Concerns and Sufia 7 tie closely to a multi-valued title field, and this ticket does not require "sort by title", I took off the "sort by title" option to make things easier.

**Comment by whunter** [comment]
Understood. Sorry that I missed that.

**Pull request merged**
